tikal_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      project: "{{ env_var('DBT_PROFILE_PROJECT') }}"
      schema: "{{ env_var('BIGQUERY_SCHEMA', 'DATASET_PREFIX') }}_DWH"
      threads: 4 # Must be a value of 1 or greater
      method: service-account
      keyfile: "{{ env_var('BIGQUERY_KEYFILE_PATH', '.keys/dev.json') }}"
