tikal_dbt:
  target: "multi"
  outputs:
    multi:
      dataset: "{{ env_var('DATASET_PREFIX') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      project: "{{ env_var('DBT_PROFILE_PROJECT') }}"
      location: "{{ env_var('DBT_PROFILE_LOCATION', 'eu') }}"
      dwh_enforce_taxonomy_project_id: "{{ env_var('DWH_ENFORCE_TAXONOMY_PROJECT_ID') }}"
      dwh_enforce_taxonomy_location: "{{ env_var('DWH_ENFORCE_TAXONOMY_LOCATION') }}"
      dwh_enforce_taxonomy_id: "{{ env_var('DWH_ENFORCE_TAXONOMY_ID')}}"
      string_mask_id: "{{ env_var('STRING_MASK_ID') }}"
      non_string_mask_id: "{{ env_var('NON_STRING_MASK_ID') }}"
      threads: 4
      type: bigquery
      method: service-account-json
      keyfile_json:
        type: "{{ env_var('DBT_PROFILE_TYPE') }}"
        project_id: "{{ env_var('DBT_PROFILE_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_PROFILE_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_PROFILE_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_PROFILE_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_PROFILE_CLIENT_ID') }}"
        auth_uri: "{{ env_var('DBT_PROFILE_AUTH_URI') }}"
        token_uri: "{{ env_var('DBT_PROFILE_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_PROFILE_AUTH_PROVIDER_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('DBT_PROFILE_CLIENT_CERT_URL') }}"