snowflake_defaults: &snowflake_defaults
  type: snowflake
  account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
  user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
  role: "{{ env_var('SNOWFLAKE_ROLE') }}"
  private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
  database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
  warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
  schema: "{{ var('target_schema', 'TEMP') }}"

elementary:
  outputs:
    default:
      type: "snowflake"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "TEMP_elementary"
      threads: 2

apex:
  target: staging
  outputs:
    staging:
      <<: *snowflake_defaults
      threads: 2
      client_session_keep_alive: False
      connect_retries: 2
      connect_timeout: 10
      retry_on_database_errors: False
      retry_all: False
      reuse_connections: True

    prod_eu:
      <<: *snowflake_defaults
      threads: 4
      client_session_keep_alive: False
      connect_retries: 3
      connect_timeout: 100
      retry_on_database_errors: False
      retry_all: False
      reuse_connections: True

    prod_us:
      <<: *snowflake_defaults
      threads: 4
      client_session_keep_alive: False
      connect_retries: 3
      connect_timeout: 100
      retry_on_database_errors: False
      retry_all: False
      reuse_connections: True
