name: Basic Checks
run-name: "Basic Checks - ${{ github.event.pull_request.number || github.ref_name }}"

concurrency:
  group: basic-checks-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

jobs:
  required:
    name: Required
    uses: vena-security/gh-actions/.github/workflows/basic-checks.yml@main
